server:
  port: 9396

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8186/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: jgt-ms-matricula-service
              uri: lb://jgt-ms-matricula-service
              predicates:
                - Path=/matriculas/**
            - id: jgt-ms-curso-service
              uri: lb://jgt-ms-curso-service
              predicates:
                - Path=/cursos/**
              # Si tu servicio real no expone /categoria/...:
              # filters:
              #   - StripPrefix=1