spring:
  application:
    name: jgt-ms-matricula-service

  datasource:
    url: jdbc:mysql://localhost:3309/matricula1?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 124578369scar@

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 3030

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8186/eureka
  instance:
    hostname: localhost

